module.exports = {
  /* config options here */
  env: {
    RAILS_ENDPOINT: process.env.RAILS_ENDPOINT,
    REACT_BASE_PATH: process.env.REACT_BASE_PATH,
    REACT_STRIPE_PUBLIC_KEY: process.env.REACT_STRIPE_PUBLIC_KEY,
    REACT_APP_MAILCHIMP_RAILS_SELF_DEFINE_TOKEN: process.env.REACT_APP_MAILCHIMP_RAILS_SELF_DEFINE_TOKEN
  }
}